// NovaPulse HRMS — Complete Enterprise Seed Data
import {
  Organization,
  Branch,
  Department,
  Designation,
  Role,
  User,
  Employee,
  Shift,
  ShiftRoster,
  ShiftSwapRequest,
  Attendance,
  AttendanceRegularization,
  LeaveType,
  LeaveBalance,
  LeaveApplication,
  Ticket,
  OnboardingInvite,
  AssetInventory,
  AssetAllocationHistory,
  OfficeGeoLocation,
  PayrollPeriod,
  Payslip,
  Holiday,
  Notification,
  AuditLog,
  SystemPolicySettings,
  UserRoleType,
  Tenant,
  TenantSubscription,
  TenantLicenseChange,
  TenantPayment,
  PayrollCycle,
  AttendancePolicy,
  OvertimeConfig,
  SalaryComponent,
  DeductionPolicy,
  TaskItem,
  TeamProject,
  WorkflowTemplate,
} from './schema';

export const INITIAL_ORGANIZATION: Organization = {
  id: 'NP-000006',
  name: 'Silaris Information Technologies',
  slug: 'silaris',
  logo: '/logo.png',
  website: 'https://www.silaris.in/',
  email: 'admin@silaris.in',
  phone: '+91 98111 55667',
  address: 'A-24/5, Mohan Cooperative Industrial Estate, Mathura Road, New Delhi, Delhi NCR - 110044, India',
  gstNumber: '07AAACS5678Q1Z2',
  udyamNumber: 'UDYAM-DL-06-0034821',
  panNumber: 'AAACS5678Q',
  createdAt: '2024-01-01T00:00:00Z',
};

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'branch-delhi-01',
    organizationId: 'org-novapulse-01',
    name: 'Delhi NCR Corporate HQ',
    code: 'DEL-HQ',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    address: 'Plot 42, Sector 62, Electronic City, Noida, Delhi NCR - 201309',
    latitude: 28.6280,
    longitude: 77.3649,
    geofenceRadiusMeters: 250,
    isHeadquarters: true,
  },
  {
    id: 'branch-mumbai-02',
    organizationId: 'org-novapulse-01',
    name: 'Mumbai Tech & Sales Hub',
    code: 'BOM-01',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    address: 'Level 5, Nesco IT Park, Western Express Highway, Goregaon East, Mumbai - 400063',
    latitude: 19.1551,
    longitude: 72.8562,
    geofenceRadiusMeters: 200,
    isHeadquarters: false,
  },
  {
    id: 'branch-bangalore-03',
    organizationId: 'org-novapulse-01',
    name: 'Bangalore R&D Center',
    code: 'BLR-01',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    address: 'Building 9A, RMZ Ecospace, Outer Ring Road, Bellandur, Bengaluru - 560103',
    latitude: 12.9260,
    longitude: 77.6835,
    geofenceRadiusMeters: 300,
    isHeadquarters: false,
  },
];

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-eng-01',
    organizationId: 'org-novapulse-01',
    name: 'Engineering & Technology',
    code: 'ENG',
    headEmployeeId: 'emp-002',
    headEmployeeName: 'Vikram Malhotra',
    color: '#3b82f6',
  },
  {
    id: 'dept-hr-02',
    organizationId: 'org-novapulse-01',
    name: 'Human Resources & People Ops',
    code: 'HR',
    headEmployeeId: 'emp-003',
    headEmployeeName: 'Ananya Sharma',
    color: '#8b5cf6',
  },
  {
    id: 'dept-sales-03',
    organizationId: 'org-novapulse-01',
    name: 'Sales & Business Growth',
    code: 'SALES',
    headEmployeeId: 'emp-004',
    headEmployeeName: 'Rajesh Nair',
    color: '#10b981',
  },
  {
    id: 'dept-it-04',
    organizationId: 'org-novapulse-01',
    name: 'IT & Workplace Security',
    code: 'IT',
    headEmployeeId: 'emp-005',
    headEmployeeName: 'Kunal Verma',
    color: '#f59e0b',
  },
  {
    id: 'dept-finance-05',
    organizationId: 'org-novapulse-01',
    name: 'Finance & Payroll Operations',
    code: 'FIN',
    headEmployeeId: 'emp-006',
    headEmployeeName: 'Pooja Iyer',
    color: '#ec4899',
  },
  {
    id: 'dept-ops-06',
    organizationId: 'org-novapulse-01',
    name: 'Customer Success & Ops',
    code: 'OPS',
    headEmployeeId: 'emp-007',
    headEmployeeName: 'Amit Saxena',
    color: '#06b6d4',
  },
];

export const INITIAL_DESIGNATIONS: Designation[] = [
  { id: 'desig-01', organizationId: 'org-novapulse-01', departmentId: 'dept-hr-02', title: 'Chief Executive Officer', level: 'C-Level' },
  { id: 'desig-02', organizationId: 'org-novapulse-01', departmentId: 'dept-eng-01', title: 'VP of Engineering', level: 'VP' },
  { id: 'desig-03', organizationId: 'org-novapulse-01', departmentId: 'dept-hr-02', title: 'Head of Human Resources', level: 'Director' },
  { id: 'desig-04', organizationId: 'org-novapulse-01', departmentId: 'dept-sales-03', title: 'Director of Business Growth', level: 'Director' },
  { id: 'desig-05', organizationId: 'org-novapulse-01', departmentId: 'dept-it-04', title: 'Lead IT & Infrastructure Engineer', level: 'Lead' },
  { id: 'desig-06', organizationId: 'org-novapulse-01', departmentId: 'dept-finance-05', title: 'Senior Payroll & Tax Specialist', level: 'Senior' },
  { id: 'desig-07', organizationId: 'org-novapulse-01', departmentId: 'dept-eng-01', title: 'Senior Full Stack Architect', level: 'Senior' },
  { id: 'desig-08', organizationId: 'org-novapulse-01', departmentId: 'dept-eng-01', title: 'Software Engineer II', level: 'Mid' },
  { id: 'desig-09', organizationId: 'org-novapulse-01', departmentId: 'dept-hr-02', title: 'HR Business Partner', level: 'Mid' },
  { id: 'desig-10', organizationId: 'org-novapulse-01', departmentId: 'dept-sales-03', title: 'Senior Account Executive', level: 'Senior' },
  { id: 'desig-11', organizationId: 'org-novapulse-01', departmentId: 'dept-ops-06', title: 'Operations Lead', level: 'Lead' },
];

const fullPerm = { view: true, create: true, edit: true, delete: true, approve: true, export: true, manage: true };
const readOnlyPerm = { view: true, create: false, edit: false, delete: false, approve: false, export: true, manage: false };
const employeeSelfPerm = { view: true, create: true, edit: true, delete: false, approve: false, export: false, manage: false };

export const INITIAL_ROLES: Role[] = [
  {
    id: 'role-super-admin',
    organizationId: 'org-novapulse-01',
    name: 'Super Admin',
    description: 'Unrestricted enterprise access across all organizations, branches, and system settings.',
    isSystem: true,
    permissions: {
      dashboard: fullPerm,
      shifts: fullPerm,
      attendance: fullPerm,
      leaves: fullPerm,
      employees: fullPerm,
      tickets: fullPerm,
      onboarding: fullPerm,
      inventory: fullPerm,
      geolocation: fullPerm,
      payroll: fullPerm,
      tasks: fullPerm,
      settings: fullPerm,
    },
  },
  {
    id: 'role-hr-admin',
    organizationId: 'org-novapulse-01',
    name: 'HR Admin',
    description: 'Full administrative access across people management, onboarding, leaves, shifts, and reports.',
    isSystem: true,
    permissions: {
      dashboard: fullPerm,
      shifts: fullPerm,
      attendance: fullPerm,
      leaves: fullPerm,
      employees: fullPerm,
      tickets: fullPerm,
      onboarding: fullPerm,
      inventory: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      geolocation: fullPerm,
      payroll: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      tasks: fullPerm,
      settings: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
    },
  },
  {
    id: 'role-manager',
    organizationId: 'org-novapulse-01',
    name: 'Manager',
    description: 'Manage reporting team members, review attendance, approve leaves & shift swaps, review team tickets.',
    isSystem: true,
    permissions: {
      dashboard: fullPerm,
      shifts: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      attendance: { view: true, create: false, edit: true, delete: false, approve: true, export: true, manage: false },
      leaves: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      employees: { view: true, create: false, edit: false, delete: false, approve: false, export: true, manage: false },
      tickets: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      onboarding: readOnlyPerm,
      inventory: readOnlyPerm,
      geolocation: readOnlyPerm,
      payroll: readOnlyPerm,
      tasks: { view: true, create: true, edit: true, delete: true, approve: true, export: true, manage: true },
      settings: readOnlyPerm,
    },
  },
  {
    id: 'role-payroll-admin',
    organizationId: 'org-novapulse-01',
    name: 'Payroll Admin',
    description: 'Manage salary structures, monthly payroll processing, statutory deductions, and tax compliance.',
    isSystem: true,
    permissions: {
      dashboard: fullPerm,
      shifts: readOnlyPerm,
      attendance: { view: true, create: false, edit: false, delete: false, approve: false, export: true, manage: false },
      leaves: { view: true, create: false, edit: false, delete: false, approve: false, export: true, manage: false },
      employees: { view: true, create: false, edit: true, delete: false, approve: false, export: true, manage: false },
      tickets: { view: true, create: true, edit: true, delete: false, approve: true, export: true, manage: false },
      onboarding: readOnlyPerm,
      inventory: readOnlyPerm,
      geolocation: readOnlyPerm,
      payroll: fullPerm,
      tasks: employeeSelfPerm,
      settings: readOnlyPerm,
    },
  },
  {
    id: 'role-employee',
    organizationId: 'org-novapulse-01',
    name: 'Employee',
    description: 'Employee Self-Service (ESS) portal for viewing profile, shifts, attendance, applying leaves, and raising tickets.',
    isSystem: true,
    permissions: {
      dashboard: employeeSelfPerm,
      shifts: employeeSelfPerm,
      attendance: employeeSelfPerm,
      leaves: employeeSelfPerm,
      employees: { view: true, create: false, edit: true, delete: false, approve: false, export: false, manage: false },
      tickets: employeeSelfPerm,
      onboarding: employeeSelfPerm,
      inventory: { view: true, create: false, edit: false, delete: false, approve: false, export: false, manage: false },
      geolocation: { view: true, create: true, edit: false, delete: false, approve: false, export: false, manage: false },
      payroll: { view: true, create: false, edit: false, delete: false, approve: false, export: false, manage: false },
      tasks: employeeSelfPerm,
      settings: { view: false, create: false, edit: false, delete: false, approve: false, export: false, manage: false },
    },
  },
];

export const INITIAL_SHIFTS: Shift[] = [
  {
    id: 'shift-gen-01',
    organizationId: 'org-novapulse-01',
    name: 'General Corporate Shift',
    code: 'GEN-09',
    startTime: '09:00',
    endTime: '18:00',
    breakDurationMinutes: 60,
    gracePeriodMinutes: 15,
    halfDayThresholdHours: 4.5,
    fullDayThresholdHours: 8.5,
    isNightShift: false,
    workingDays: [1, 2, 3, 4, 5],
    weeklyOffs: [0, 6],
    color: '#8b5cf6',
  },
  {
    id: 'shift-morning-02',
    organizationId: 'org-novapulse-01',
    name: 'Morning Operations Shift (A)',
    code: 'MORN-06',
    startTime: '06:00',
    endTime: '15:00',
    breakDurationMinutes: 60,
    gracePeriodMinutes: 10,
    halfDayThresholdHours: 4.0,
    fullDayThresholdHours: 8.0,
    isNightShift: false,
    workingDays: [1, 2, 3, 4, 5, 6],
    weeklyOffs: [0],
    color: '#3b82f6',
  },
  {
    id: 'shift-evening-03',
    organizationId: 'org-novapulse-01',
    name: 'Evening Support Shift (B)',
    code: 'EVE-14',
    startTime: '14:00',
    endTime: '23:00',
    breakDurationMinutes: 60,
    gracePeriodMinutes: 15,
    halfDayThresholdHours: 4.0,
    fullDayThresholdHours: 8.0,
    isNightShift: false,
    workingDays: [1, 2, 3, 4, 5],
    weeklyOffs: [0, 6],
    color: '#10b981',
  },
  {
    id: 'shift-night-04',
    organizationId: 'org-novapulse-01',
    name: 'Night Infrastructure Shift',
    code: 'NGT-22',
    startTime: '22:00',
    endTime: '07:00',
    breakDurationMinutes: 60,
    gracePeriodMinutes: 15,
    halfDayThresholdHours: 4.0,
    fullDayThresholdHours: 8.0,
    isNightShift: true,
    workingDays: [1, 2, 3, 4, 5],
    weeklyOffs: [0, 6],
    color: '#f59e0b',
  },
];

export const INITIAL_LEAVE_TYPES: LeaveType[] = [
  {
    id: 'lt-cl-01',
    organizationId: 'org-novapulse-01',
    name: 'Casual Leave (CL)',
    code: 'CL',
    description: 'For unforeseen personal emergencies and brief personal work.',
    annualQuota: 12,
    accrualFrequency: 'monthly',
    carryForwardMax: 0,
    isHalfDayAllowed: true,
    requiresDoc: false,
    isPaid: true,
    color: '#3b82f6',
  },
  {
    id: 'lt-sl-02',
    organizationId: 'org-novapulse-01',
    name: 'Sick Leave (SL)',
    code: 'SL',
    description: 'Medical and sickness leave with doctor verification if > 2 consecutive days.',
    annualQuota: 10,
    accrualFrequency: 'annual',
    carryForwardMax: 5,
    isHalfDayAllowed: true,
    requiresDoc: true,
    isPaid: true,
    color: '#ef4444',
  },
  {
    id: 'lt-el-03',
    organizationId: 'org-novapulse-01',
    name: 'Earned / Privilege Leave (EL)',
    code: 'EL',
    description: 'Annual accrued vacation and planned leaves.',
    annualQuota: 18,
    accrualFrequency: 'monthly',
    carryForwardMax: 30,
    isHalfDayAllowed: false,
    requiresDoc: false,
    isPaid: true,
    color: '#10b981',
  },
  {
    id: 'lt-co-04',
    organizationId: 'org-novapulse-01',
    name: 'Compensatory Off (Comp-Off)',
    code: 'CO',
    description: 'Earned by working on weekend shifts, public holidays, or critical deployments.',
    annualQuota: 6,
    accrualFrequency: 'monthly',
    carryForwardMax: 3,
    isHalfDayAllowed: true,
    requiresDoc: false,
    isPaid: true,
    color: '#8b5cf6',
  },
  {
    id: 'lt-lop-05',
    organizationId: 'org-novapulse-01',
    name: 'Loss of Pay (LOP / Unpaid)',
    code: 'LOP',
    description: 'Unpaid leaves taken after exhaust of authorized quotas.',
    annualQuota: 99,
    accrualFrequency: 'annual',
    carryForwardMax: 0,
    isHalfDayAllowed: true,
    requiresDoc: false,
    isPaid: false,
    color: '#64748b',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    employeeCode: 'NP-1001',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-hr-02',
    designationId: 'desig-01',
    firstName: 'Yatender',
    lastName: 'Sharma',
    email: 'yatender@novapulse.co.in',
    phone: '+91 87966 23604',
    personalEmail: 'yatender.sharma@gmail.com',
    dob: '1988-06-15',
    gender: 'Male',
    bloodGroup: 'O+',
    maritalStatus: 'Married',
    joiningDate: '2023-01-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 60,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 125000,
      hra: 62500,
      conveyanceAllowance: 8000,
      specialAllowance: 45000,
      medicalAllowance: 4500,
      otherAllowances: 5000,
      grossSalary: 250000,
      ctc: 3200000,
    },
    bankDetails: {
      accountHolderName: 'Yatender Sharma',
      accountNumber: '91802003892341',
      bankName: 'HDFC Bank Ltd.',
      ifscCode: 'HDFC0001234',
      branchName: 'Sector 62, Noida',
    },
    statutoryDetails: {
      pan: 'AAACS1902K',
      aadhaar: 'XXXX-XXXX-8912',
      uan: '100923849102',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Uttar Pradesh',
    },
    emergencyContact: {
      name: 'Sunita Sharma',
      relationship: 'Spouse',
      phone: '+91 98112 34567',
    },
    documents: [
      { id: 'doc-01', type: 'PAN', name: 'PAN_Card.pdf', fileUrl: '/docs/pan.pdf', uploadDate: '2023-01-02', status: 'Verified' },
      { id: 'doc-02', type: 'Aadhaar', name: 'Aadhaar.pdf', fileUrl: '/docs/aadhaar.pdf', uploadDate: '2023-01-02', status: 'Verified' },
    ],
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Tower B, Mahagun Moderne, Sector 78, Noida - 201301',
    permanentAddress: 'Tower B, Mahagun Moderne, Sector 78, Noida - 201301',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-002',
    employeeCode: 'NP-1002',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-eng-01',
    designationId: 'desig-02',
    reportingManagerId: 'emp-001',
    firstName: 'Vikram',
    lastName: 'Malhotra',
    email: 'vikram.m@novapulse.co.in',
    phone: '+91 98765 43210',
    personalEmail: 'vikram.malhotra@yahoo.com',
    dob: '1990-09-22',
    gender: 'Male',
    bloodGroup: 'B+',
    maritalStatus: 'Married',
    joiningDate: '2023-02-15',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 60,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 95000,
      hra: 47500,
      conveyanceAllowance: 5000,
      specialAllowance: 38000,
      medicalAllowance: 4500,
      otherAllowances: 0,
      grossSalary: 190000,
      ctc: 2450000,
    },
    bankDetails: {
      accountHolderName: 'Vikram Malhotra',
      accountNumber: '00291040001928',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000029',
      branchName: 'Connaught Place, New Delhi',
    },
    statutoryDetails: {
      pan: 'BKMPM4821N',
      aadhaar: 'XXXX-XXXX-4532',
      uan: '100874920194',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Delhi',
    },
    emergencyContact: {
      name: 'Pooja Malhotra',
      relationship: 'Spouse',
      phone: '+91 98711 22334',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'C-42, Defence Colony, New Delhi - 110024',
    createdAt: '2023-02-15T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-003',
    employeeCode: 'NP-1003',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-hr-02',
    designationId: 'desig-03',
    reportingManagerId: 'emp-001',
    firstName: 'Ananya',
    lastName: 'Sharma',
    email: 'ananya.hr@novapulse.co.in',
    phone: '+91 98109 87654',
    personalEmail: 'ananya.sharma@outlook.com',
    dob: '1992-11-04',
    gender: 'Female',
    bloodGroup: 'A+',
    maritalStatus: 'Single',
    joiningDate: '2023-03-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 45,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 75000,
      hra: 37500,
      conveyanceAllowance: 4000,
      specialAllowance: 29500,
      medicalAllowance: 4000,
      otherAllowances: 0,
      grossSalary: 150000,
      ctc: 1950000,
    },
    bankDetails: {
      accountHolderName: 'Ananya Sharma',
      accountNumber: '50100293849102',
      bankName: 'HDFC Bank Ltd.',
      ifscCode: 'HDFC0000456',
      branchName: 'Sector 18, Noida',
    },
    statutoryDetails: {
      pan: 'CPNPS8472M',
      aadhaar: 'XXXX-XXXX-9128',
      uan: '100482910394',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Uttar Pradesh',
    },
    emergencyContact: {
      name: 'Ramesh Sharma',
      relationship: 'Father',
      phone: '+91 98100 11223',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Flat 402, ATS Greens, Sector 50, Noida',
    createdAt: '2023-03-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-004',
    employeeCode: 'NP-1004',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-mumbai-02',
    departmentId: 'dept-sales-03',
    designationId: 'desig-04',
    reportingManagerId: 'emp-001',
    firstName: 'Rajesh',
    lastName: 'Nair',
    email: 'rajesh.nair@novapulse.co.in',
    phone: '+91 97690 12345',
    dob: '1989-03-18',
    gender: 'Male',
    bloodGroup: 'AB+',
    maritalStatus: 'Married',
    joiningDate: '2023-04-10',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 45,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 80000,
      hra: 40000,
      conveyanceAllowance: 5000,
      specialAllowance: 31000,
      medicalAllowance: 4000,
      otherAllowances: 0,
      grossSalary: 160000,
      ctc: 2100000,
    },
    bankDetails: {
      accountHolderName: 'Rajesh Nair',
      accountNumber: '192837465019',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0000123',
      branchName: 'Andheri East, Mumbai',
    },
    statutoryDetails: {
      pan: 'BNPRN9382L',
      aadhaar: 'XXXX-XXXX-3829',
      uan: '100918273645',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Maharashtra',
    },
    emergencyContact: {
      name: 'Divya Nair',
      relationship: 'Spouse',
      phone: '+91 97690 54321',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Oakwood Apts, Powai, Mumbai - 400076',
    createdAt: '2023-04-10T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-005',
    employeeCode: 'NP-1005',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-it-04',
    designationId: 'desig-05',
    reportingManagerId: 'emp-002',
    firstName: 'Kunal',
    lastName: 'Verma',
    email: 'kunal.v@novapulse.co.in',
    phone: '+91 98118 76543',
    dob: '1993-08-12',
    gender: 'Male',
    bloodGroup: 'O-',
    maritalStatus: 'Single',
    joiningDate: '2023-05-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 30,
    assignedShiftId: 'shift-morning-02',
    salaryStructure: {
      basicSalary: 45000,
      hra: 22500,
      conveyanceAllowance: 3000,
      specialAllowance: 16500,
      medicalAllowance: 3000,
      otherAllowances: 0,
      grossSalary: 90000,
      ctc: 1180000,
    },
    bankDetails: {
      accountHolderName: 'Kunal Verma',
      accountNumber: '382910482910',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0000182',
      branchName: 'Sector 62, Noida',
    },
    statutoryDetails: {
      pan: 'CVRPK4819P',
      aadhaar: 'XXXX-XXXX-1928',
      uan: '100492817294',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Uttar Pradesh',
    },
    emergencyContact: {
      name: 'Sunil Verma',
      relationship: 'Father',
      phone: '+91 98118 11111',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Sector 55, Noida',
    createdAt: '2023-05-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-006',
    employeeCode: 'NP-1006',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-finance-05',
    designationId: 'desig-06',
    reportingManagerId: 'emp-001',
    firstName: 'Pooja',
    lastName: 'Iyer',
    email: 'pooja.iyer@novapulse.co.in',
    phone: '+91 99201 23456',
    dob: '1991-01-20',
    gender: 'Female',
    bloodGroup: 'B-',
    maritalStatus: 'Married',
    joiningDate: '2023-06-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 45,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 60000,
      hra: 30000,
      conveyanceAllowance: 4000,
      specialAllowance: 22000,
      medicalAllowance: 4000,
      otherAllowances: 0,
      grossSalary: 120000,
      ctc: 1560000,
    },
    bankDetails: {
      accountHolderName: 'Pooja Iyer',
      accountNumber: '920192837461',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0004928',
      branchName: 'Indirapuram, Ghaziabad',
    },
    statutoryDetails: {
      pan: 'AIYPP9381Q',
      aadhaar: 'XXXX-XXXX-7362',
      uan: '100837291048',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Uttar Pradesh',
    },
    emergencyContact: {
      name: 'Ganesh Iyer',
      relationship: 'Spouse',
      phone: '+91 99201 65432',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Ahinsa Khand, Indirapuram, Ghaziabad',
    createdAt: '2023-06-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-007',
    employeeCode: 'NP-1007',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-bangalore-03',
    departmentId: 'dept-eng-01',
    designationId: 'desig-07',
    reportingManagerId: 'emp-002',
    firstName: 'Rohan',
    lastName: 'Deshmukh',
    email: 'rohan.d@novapulse.co.in',
    phone: '+91 98450 98765',
    dob: '1994-04-14',
    gender: 'Male',
    bloodGroup: 'O+',
    maritalStatus: 'Single',
    joiningDate: '2023-07-15',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 30,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 65000,
      hra: 32500,
      conveyanceAllowance: 4000,
      specialAllowance: 24500,
      medicalAllowance: 4000,
      otherAllowances: 0,
      grossSalary: 130000,
      ctc: 1690000,
    },
    bankDetails: {
      accountHolderName: 'Rohan Deshmukh',
      accountNumber: '492810394829',
      bankName: 'HDFC Bank Ltd.',
      ifscCode: 'HDFC0000829',
      branchName: 'Koramangala, Bengaluru',
    },
    statutoryDetails: {
      pan: 'DSHPR8291K',
      aadhaar: 'XXXX-XXXX-2918',
      uan: '100748291038',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Karnataka',
    },
    emergencyContact: {
      name: 'Ashok Deshmukh',
      relationship: 'Father',
      phone: '+91 98450 11122',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'HSR Layout Sector 2, Bengaluru - 560102',
    createdAt: '2023-07-15T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-008',
    employeeCode: 'NP-1008',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-bangalore-03',
    departmentId: 'dept-eng-01',
    designationId: 'desig-08',
    reportingManagerId: 'emp-007',
    firstName: 'Priya',
    lastName: 'Sundaram',
    email: 'priya.s@novapulse.co.in',
    phone: '+91 98451 23456',
    dob: '1996-12-08',
    gender: 'Female',
    bloodGroup: 'A+',
    maritalStatus: 'Single',
    joiningDate: '2023-09-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 30,
    assignedShiftId: 'shift-evening-03',
    salaryStructure: {
      basicSalary: 40000,
      hra: 20000,
      conveyanceAllowance: 3000,
      specialAllowance: 14000,
      medicalAllowance: 3000,
      otherAllowances: 0,
      grossSalary: 80000,
      ctc: 1040000,
    },
    bankDetails: {
      accountHolderName: 'Priya Sundaram',
      accountNumber: '291039482910',
      bankName: 'Canara Bank',
      ifscCode: 'CNRB0001928',
      branchName: 'Indiranagar, Bengaluru',
    },
    statutoryDetails: {
      pan: 'SNDPP4928J',
      aadhaar: 'XXXX-XXXX-6391',
      uan: '100638291048',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Karnataka',
    },
    emergencyContact: {
      name: 'Sundaram V',
      relationship: 'Father',
      phone: '+91 98451 99887',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Indiranagar 100ft Road, Bengaluru',
    createdAt: '2023-09-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-009',
    employeeCode: 'NP-1009',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    departmentId: 'dept-hr-02',
    designationId: 'desig-09',
    reportingManagerId: 'emp-003',
    firstName: 'Sneha',
    lastName: 'Kapoor',
    email: 'sneha.k@novapulse.co.in',
    phone: '+91 98188 33445',
    dob: '1995-02-17',
    gender: 'Female',
    bloodGroup: 'B+',
    maritalStatus: 'Single',
    joiningDate: '2023-10-10',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 30,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 35000,
      hra: 17500,
      conveyanceAllowance: 3000,
      specialAllowance: 11500,
      medicalAllowance: 3000,
      otherAllowances: 0,
      grossSalary: 70000,
      ctc: 910000,
    },
    bankDetails: {
      accountHolderName: 'Sneha Kapoor',
      accountNumber: '839201948291',
      bankName: 'HDFC Bank Ltd.',
      ifscCode: 'HDFC0000182',
      branchName: 'Sector 50, Noida',
    },
    statutoryDetails: {
      pan: 'KPRSK3829L',
      aadhaar: 'XXXX-XXXX-9482',
      uan: '100482910492',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Uttar Pradesh',
    },
    emergencyContact: {
      name: 'Neeta Kapoor',
      relationship: 'Mother',
      phone: '+91 98188 99887',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Sector 61, Noida',
    createdAt: '2023-10-10T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'emp-010',
    employeeCode: 'NP-1010',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-mumbai-02',
    departmentId: 'dept-sales-03',
    designationId: 'desig-10',
    reportingManagerId: 'emp-004',
    firstName: 'Arjun',
    lastName: 'Mehta',
    email: 'arjun.m@novapulse.co.in',
    phone: '+91 98200 44556',
    dob: '1993-07-29',
    gender: 'Male',
    bloodGroup: 'O+',
    maritalStatus: 'Single',
    joiningDate: '2023-11-01',
    employmentType: 'Full-time',
    employmentStatus: 'Active',
    noticePeriodDays: 30,
    assignedShiftId: 'shift-gen-01',
    salaryStructure: {
      basicSalary: 45000,
      hra: 22500,
      conveyanceAllowance: 4000,
      specialAllowance: 15500,
      medicalAllowance: 3000,
      otherAllowances: 0,
      grossSalary: 90000,
      ctc: 1180000,
    },
    bankDetails: {
      accountHolderName: 'Arjun Mehta',
      accountNumber: '938201948291',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0000492',
      branchName: 'Bandra West, Mumbai',
    },
    statutoryDetails: {
      pan: 'MHTAM4829K',
      aadhaar: 'XXXX-XXXX-1029',
      uan: '100392810482',
      pfEligible: true,
      esiEligible: false,
      professionalTaxState: 'Maharashtra',
    },
    emergencyContact: {
      name: 'Sunil Mehta',
      relationship: 'Father',
      phone: '+91 98200 11223',
    },
    documents: [],
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80',
    currentAddress: 'Bandra West, Mumbai',
    createdAt: '2023-11-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-001',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-001',
    email: 'yatender@novapulse.co.in',
    fullName: 'Yatender Sharma (CEO & Super Admin)',
    roleId: 'role-super-admin',
    roleName: 'Super Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'user-003',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-003',
    email: 'ananya.hr@novapulse.co.in',
    fullName: 'Ananya Sharma (HR Admin)',
    roleId: 'role-hr-admin',
    roleName: 'HR Admin',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'user-002',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-002',
    email: 'vikram.m@novapulse.co.in',
    fullName: 'Vikram Malhotra (Engineering Manager)',
    roleId: 'role-manager',
    roleName: 'Manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'user-006',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-006',
    email: 'pooja.iyer@novapulse.co.in',
    fullName: 'Pooja Iyer (Payroll Admin)',
    roleId: 'role-payroll-admin',
    roleName: 'Payroll Admin',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'user-007',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-007',
    email: 'rohan.d@novapulse.co.in',
    fullName: 'Rohan Deshmukh (Software Architect)',
    roleId: 'role-employee',
    roleName: 'Employee',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
];

// Helper to generate seed leave balances
export const INITIAL_LEAVE_BALANCES: LeaveBalance[] = INITIAL_EMPLOYEES.flatMap(emp => [
  { id: `lb-${emp.id}-cl`, organizationId: 'org-novapulse-01', employeeId: emp.id, leaveTypeId: 'lt-cl-01', year: 2026, allocated: 12, used: 2, pending: 1, balance: 9 },
  { id: `lb-${emp.id}-sl`, organizationId: 'org-novapulse-01', employeeId: emp.id, leaveTypeId: 'lt-sl-02', year: 2026, allocated: 10, used: 1, pending: 0, balance: 9 },
  { id: `lb-${emp.id}-el`, organizationId: 'org-novapulse-01', employeeId: emp.id, leaveTypeId: 'lt-el-03', year: 2026, allocated: 18, used: 3, pending: 0, balance: 15 },
  { id: `lb-${emp.id}-co`, organizationId: 'org-novapulse-01', employeeId: emp.id, leaveTypeId: 'lt-co-04', year: 2026, allocated: 3, used: 0, pending: 0, balance: 3 },
  { id: `lb-${emp.id}-lop`, organizationId: 'org-novapulse-01', employeeId: emp.id, leaveTypeId: 'lt-lop-05', year: 2026, allocated: 0, used: 0, pending: 0, balance: 0 },
]);

export const INITIAL_LEAVE_APPLICATIONS: LeaveApplication[] = [
  {
    id: 'la-001',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-008', // Priya
    leaveTypeId: 'lt-cl-01',
    startDate: '2026-09-24',
    endDate: '2026-09-25',
    totalDays: 2,
    isHalfDay: false,
    reason: 'Attending family wedding ceremony in Chennai.',
    status: 'pending',
    approverEmployeeId: 'emp-007',
    createdAt: '2026-09-21T10:30:00Z',
  },
  {
    id: 'la-002',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-005', // Kunal
    leaveTypeId: 'lt-sl-02',
    startDate: '2026-09-15',
    endDate: '2026-09-16',
    totalDays: 2,
    isHalfDay: false,
    reason: 'Severe viral fever and eye strain, advised bed rest.',
    status: 'approved',
    approverEmployeeId: 'emp-002',
    createdAt: '2026-09-14T14:10:00Z',
    approvedAt: '2026-09-14T16:00:00Z',
  },
  {
    id: 'la-003',
    organizationId: 'org-novapulse-01',
    employeeId: 'emp-010', // Arjun
    leaveTypeId: 'lt-el-03',
    startDate: '2026-10-01',
    endDate: '2026-10-05',
    totalDays: 5,
    isHalfDay: false,
    reason: 'Planned vacation and Diwali festival break.',
    status: 'approved',
    approverEmployeeId: 'emp-004',
    createdAt: '2026-09-18T09:00:00Z',
    approvedAt: '2026-09-19T11:30:00Z',
  },
];

export const INITIAL_SHIFT_SWAPS: ShiftSwapRequest[] = [
  {
    id: 'swap-001',
    organizationId: 'org-novapulse-01',
    requesterEmployeeId: 'emp-008', // Priya (Evening Shift)
    targetEmployeeId: 'emp-007',    // Rohan (General Shift)
    requesterDate: '2026-09-28',
    requesterShiftId: 'shift-evening-03',
    targetDate: '2026-09-28',
    targetShiftId: 'shift-gen-01',
    reason: 'Need to attend an early morning technical webinar on 28th Sep.',
    status: 'peer_accepted',
    peerResponseDate: '2026-09-21T14:20:00Z',
    managerId: 'emp-002',
    createdAt: '2026-09-21T11:00:00Z',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt-001',
    organizationId: 'org-novapulse-01',
    ticketCode: 'TKT-2026-081',
    employeeId: 'emp-007',
    category: 'IT',
    subject: 'Request for secondary 27" 4K Monitor for UI Development',
    description: 'Require second monitor for dual-screen productivity in Bengaluru office.',
    priority: 'Medium',
    status: 'In Progress',
    assignedToEmployeeId: 'emp-005',
    assignedDepartmentId: 'dept-it-04',
    attachments: [],
    slaHours: 48,
    isSlaBreached: false,
    comments: [
      {
        id: 'tcom-01',
        ticketId: 'tkt-001',
        authorUserId: 'user-001',
        authorName: 'Kunal Verma',
        authorRole: 'IT Lead',
        message: 'Dell 27-inch 4K monitor has been requisitioned from IT storage. Delivery scheduled by tomorrow afternoon.',
        isInternalOnly: false,
        createdAt: '2026-09-21T12:00:00Z',
      }
    ],
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-21T12:00:00Z',
  },
  {
    id: 'tkt-002',
    organizationId: 'org-novapulse-01',
    ticketCode: 'TKT-2026-082',
    employeeId: 'emp-008',
    category: 'Payroll',
    subject: 'Clarification regarding Tax Deduction (TDS) on August Payslip',
    description: 'August salary slip showed higher TDS deduction. Requesting updated tax computation sheet.',
    priority: 'High',
    status: 'Open',
    assignedToEmployeeId: 'emp-006',
    assignedDepartmentId: 'dept-finance-05',
    attachments: [],
    slaHours: 24,
    isSlaBreached: false,
    comments: [],
    createdAt: '2026-09-21T15:30:00Z',
    updatedAt: '2026-09-21T15:30:00Z',
  },
  {
    id: 'tkt-003',
    organizationId: 'org-novapulse-01',
    ticketCode: 'TKT-2026-079',
    employeeId: 'emp-010',
    category: 'HR',
    subject: 'Health Insurance Card / TPA ID card copy needed',
    description: 'Need corporate cashless health insurance mediclaim card for dependent parents.',
    priority: 'Low',
    status: 'Resolved',
    assignedToEmployeeId: 'emp-009',
    assignedDepartmentId: 'dept-hr-02',
    attachments: [],
    slaHours: 72,
    isSlaBreached: false,
    resolutionNotes: 'Sent digital e-card PDF via direct email and attached to employee portal.',
    comments: [],
    resolvedAt: '2026-09-19T17:00:00Z',
    createdAt: '2026-09-18T09:15:00Z',
    updatedAt: '2026-09-19T17:00:00Z',
  }
];

export const INITIAL_ONBOARDING_INVITES: OnboardingInvite[] = [
  {
    id: 'onb-001',
    organizationId: 'org-novapulse-01',
    token: 'np-inv-9a8f7b2c',
    candidateName: 'Akash Deep',
    candidateEmail: 'akash.deep.tech@gmail.com',
    candidatePhone: '+91 98712 34560',
    departmentId: 'dept-eng-01',
    designationId: 'desig-08',
    branchId: 'branch-delhi-01',
    expectedJoiningDate: '2026-10-01',
    assignedShiftId: 'shift-gen-01',
    offeredGrossSalary: 85000,
    status: 'submitted',
    submittedData: {
      firstName: 'Akash',
      lastName: 'Deep',
      personalEmail: 'akash.deep.tech@gmail.com',
      phone: '+91 98712 34560',
      dob: '1997-05-19',
      gender: 'Male',
      bloodGroup: 'B+',
      currentAddress: 'Sector 62, Noida, UP',
      permanentAddress: 'Civil Lines, Kanpur, UP',
      emergencyContact: { name: 'S. K. Deep', relationship: 'Father', phone: '+91 98712 99999' },
      bankDetails: { accountHolderName: 'Akash Deep', accountNumber: '501004928102', bankName: 'HDFC Bank', ifscCode: 'HDFC0000182', branchName: 'Noida' },
      statutoryDetails: { pan: 'ADEPK8291M', aadhaar: 'XXXX-XXXX-7182', pfEligible: true, esiEligible: false, professionalTaxState: 'Uttar Pradesh' },
      education: [{ degree: 'B.Tech in Computer Science', institution: 'AKTU', passingYear: 2019, percentage: '82%' }],
      previousExperience: [{ company: 'Infosys Ltd.', designation: 'Systems Engineer', fromDate: '2019-07-01', toDate: '2026-08-31', ctc: '7.5 LPA' }],
      documents: [
        { type: 'PAN', name: 'Pan_Akash.pdf', fileUrl: '/docs/pan.pdf', uploadDate: '2026-09-20' },
        { type: 'Aadhaar', name: 'Aadhaar_Akash.pdf', fileUrl: '/docs/aadhaar.pdf', uploadDate: '2026-09-20' },
      ]
    },
    createdAt: '2026-09-18T10:00:00Z',
    expiresAt: '2026-10-05T23:59:59Z',
  },
  {
    id: 'onb-002',
    organizationId: 'org-novapulse-01',
    token: 'np-inv-1b4e5f8a',
    candidateName: 'Meera Nambiar',
    candidateEmail: 'meera.nambiar@gmail.com',
    candidatePhone: '+91 98450 11229',
    departmentId: 'dept-sales-03',
    designationId: 'desig-10',
    branchId: 'branch-bangalore-03',
    expectedJoiningDate: '2026-10-15',
    assignedShiftId: 'shift-gen-01',
    offeredGrossSalary: 75000,
    status: 'sent',
    createdAt: '2026-09-21T09:00:00Z',
    expiresAt: '2026-10-10T23:59:59Z',
  }
];

export const INITIAL_ASSETS: AssetInventory[] = [
  {
    id: 'ast-001',
    organizationId: 'org-novapulse-01',
    assetTag: 'NP-LAP-001',
    name: 'Apple MacBook Pro 14" M3 Pro',
    category: 'Laptop',
    brand: 'Apple',
    model: 'MacBook Pro 14-inch (18GB/512GB)',
    serialNumber: 'C02G401ZMD6M',
    purchaseDate: '2024-01-15',
    purchaseCost: 199900,
    warrantyExpiryDate: '2027-01-14',
    vendorName: 'Imagine Apple Premium Reseller',
    vendorContact: '+91 120 4912000',
    condition: 'Excellent',
    status: 'Allocated',
    allocatedToEmployeeId: 'emp-002', // Vikram
    allocatedDate: '2024-01-16',
    branchId: 'branch-delhi-01',
    notes: 'Configured with full disk encryption and MDM policy.',
  },
  {
    id: 'ast-002',
    organizationId: 'org-novapulse-01',
    assetTag: 'NP-LAP-002',
    name: 'Lenovo ThinkPad T14s Gen 4',
    category: 'Laptop',
    brand: 'Lenovo',
    model: 'ThinkPad T14s (AMD Ryzen 7, 32GB/1TB)',
    serialNumber: 'PF3Z8912KL',
    purchaseDate: '2024-02-10',
    purchaseCost: 125000,
    warrantyExpiryDate: '2027-02-09',
    vendorName: 'Lenovo Commercial Store',
    vendorContact: '+91 80 49128392',
    condition: 'Excellent',
    status: 'Allocated',
    allocatedToEmployeeId: 'emp-007', // Rohan
    allocatedDate: '2024-02-15',
    branchId: 'branch-bangalore-03',
  },
  {
    id: 'ast-003',
    organizationId: 'org-novapulse-01',
    assetTag: 'NP-BIO-001',
    name: 'NovaPulse Biometric Face & Fingerprint Terminal',
    category: 'Biometric Device',
    brand: 'NovaPulse AI',
    model: 'NP-FaceBio 5000 Enterprise',
    serialNumber: 'NP-BIO-DEL-0192',
    purchaseDate: '2023-05-10',
    purchaseCost: 45000,
    warrantyExpiryDate: '2026-05-09',
    vendorName: 'NovaPulse Hardware Solutions',
    vendorContact: '+91 87966 23604',
    condition: 'Brand New',
    status: 'Allocated',
    branchId: 'branch-delhi-01',
    notes: 'Deployed at Delhi NCR HQ Reception gate with Real-time Cloud Push.',
  },
  {
    id: 'ast-004',
    organizationId: 'org-novapulse-01',
    assetTag: 'NP-MON-001',
    name: 'Dell UltraSharp 27" 4K USB-C Monitor',
    category: 'Desktop',
    brand: 'Dell',
    model: 'U2723QE',
    serialNumber: 'CN-0982-DEL-491',
    purchaseDate: '2024-03-01',
    purchaseCost: 48500,
    warrantyExpiryDate: '2027-02-28',
    vendorName: 'Dell India Enterprise Direct',
    vendorContact: '1800-425-4026',
    condition: 'Brand New',
    status: 'Available',
    branchId: 'branch-delhi-01',
  },
];

export const INITIAL_GEO_LOCATIONS: OfficeGeoLocation[] = [
  {
    id: 'geo-delhi-01',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-delhi-01',
    name: 'Delhi NCR Corporate HQ Geofence',
    address: 'Plot 42, Sector 62, Electronic City, Noida, UP - 201309',
    latitude: 28.6280,
    longitude: 77.3649,
    radiusMeters: 250,
    isRestricted: true,
    isActive: true,
  },
  {
    id: 'geo-mumbai-02',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-mumbai-02',
    name: 'Mumbai Tech Hub Geofence',
    address: 'Level 5, Nesco IT Park, Goregaon East, Mumbai - 400063',
    latitude: 19.1551,
    longitude: 72.8562,
    radiusMeters: 200,
    isRestricted: true,
    isActive: true,
  },
  {
    id: 'geo-blr-03',
    organizationId: 'org-novapulse-01',
    branchId: 'branch-bangalore-03',
    name: 'Bangalore R&D Geofence',
    address: 'Building 9A, RMZ Ecospace, Bellandur, Bengaluru - 560103',
    latitude: 12.9260,
    longitude: 77.6835,
    radiusMeters: 300,
    isRestricted: true,
    isActive: true,
  },
];

export const INITIAL_HOLIDAYS: Holiday[] = [
  { id: 'hol-01', organizationId: 'org-novapulse-01', name: 'Republic Day', date: '2026-01-26', isOptional: false, description: 'National Holiday' },
  { id: 'hol-02', organizationId: 'org-novapulse-01', name: 'Holi Festival of Colors', date: '2026-03-04', isOptional: false },
  { id: 'hol-03', organizationId: 'org-novapulse-01', name: 'Eid-ul-Fitr', date: '2026-03-21', isOptional: false },
  { id: 'hol-04', organizationId: 'org-novapulse-01', name: 'Independence Day', date: '2026-08-15', isOptional: false, description: 'National Holiday' },
  { id: 'hol-05', organizationId: 'org-novapulse-01', name: 'Mahatma Gandhi Jayanti', date: '2026-10-02', isOptional: false, description: 'National Holiday' },
  { id: 'hol-06', organizationId: 'org-novapulse-01', name: 'Dussehra (Vijayadashami)', date: '2026-10-20', isOptional: false },
  { id: 'hol-07', organizationId: 'org-novapulse-01', name: 'Diwali (Deepavali)', date: '2026-11-08', isOptional: false },
  { id: 'hol-08', organizationId: 'org-novapulse-01', name: 'Christmas Day', date: '2026-12-25', isOptional: false },
];

export const INITIAL_SYSTEM_SETTINGS: SystemPolicySettings = {
  attendance: {
    defaultGracePeriodMinutes: 15,
    halfDayWorkHours: 4.5,
    fullDayWorkHours: 8.5,
    autoDeductLateAfterOccurrences: 3,
    overtimeThresholdHours: 9.0,
    geofenceStrictEnforcement: true,
  },
  leave: {
    maxConsecutiveLeaveDays: 15,
    advanceNoticeDaysRequired: 2,
    allowNegativeBalance: false,
  },
  payroll: {
    pfCeilingAmount: 15000,
    pfEmployeeRatePercent: 12.0,
    pfEmployerRatePercent: 12.0,
    esiWageThreshold: 21000,
    esiEmployeeRatePercent: 0.75,
    esiEmployerRatePercent: 3.25,
    standardWorkingDaysPerMonth: 26,
  },
};

// Generate realistic Attendance for September 2026 (Dates 1 to 21)
export function generateSeedAttendance(): Attendance[] {
  const attendanceList: Attendance[] = [];
  const employees = INITIAL_EMPLOYEES;
  const dates = [
    '2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04', '2026-09-05',
    '2026-09-07', '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11',
    '2026-09-14', '2026-09-15', '2026-09-16', '2026-09-17', '2026-09-18',
    '2026-09-21'
  ];

  let idCounter = 1;
  dates.forEach(date => {
    employees.forEach(emp => {
      // Deterministic realistic variance
      const isLate = (emp.id === 'emp-005' && date === '2026-09-08') || (emp.id === 'emp-008' && date === '2026-09-10');
      const isLeave = (emp.id === 'emp-005' && (date === '2026-09-15' || date === '2026-09-16'));
      const isWFH = (emp.id === 'emp-007' && date === '2026-09-04');
      const isHalfDay = (emp.id === 'emp-009' && date === '2026-09-11');

      let status: any = 'Present';
      let checkIn = '08:56:00';
      let checkOut = '18:05:00';
      let workDuration = 549; // ~9h 9m
      let lateMinutes = 0;

      if (isLeave) {
        status = 'Leave';
        checkIn = undefined as any;
        checkOut = undefined as any;
        workDuration = 0;
      } else if (isLate) {
        status = 'Late Arrival';
        checkIn = '09:28:00';
        checkOut = '18:30:00';
        lateMinutes = 28;
        workDuration = 542;
      } else if (isWFH) {
        status = 'Work From Home';
        checkIn = '09:00:00';
        checkOut = '18:00:00';
        workDuration = 540;
      } else if (isHalfDay) {
        status = 'Half-Day';
        checkIn = '09:00:00';
        checkOut = '13:30:00';
        workDuration = 270;
      }

      attendanceList.push({
        id: `att-${idCounter++}`,
        organizationId: 'org-novapulse-01',
        employeeId: emp.id,
        date,
        shiftId: emp.assignedShiftId,
        checkIn,
        checkOut,
        status,
        workDurationMinutes: workDuration,
        lateMinutes,
        earlyDepartureMinutes: 0,
        overtimeMinutes: 0,
        isRegularized: false,
        punchSource: isWFH ? 'Web Portal' : 'Biometric Machine',
        checkInLocation: {
          lat: 28.6280,
          lng: 77.3649,
          inGeofence: true,
          address: 'Delhi NCR Corporate HQ, Noida',
        },
      });
    });
  });

  return attendanceList;
}

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    organizationId: 'org-novapulse-01',
    recipientUserId: 'user-002', // Vikram Malhotra
    recipientEmployeeId: 'emp-002',
    title: 'Shift Swap Approval Requested',
    message: 'Priya Sundaram and Rohan Deshmukh have agreed to a shift swap for 28th Sep. Awaiting your approval.',
    type: 'shift',
    link: '/shifts',
    isRead: false,
    createdAt: '2026-09-21T14:25:00Z',
  },
  {
    id: 'notif-002',
    organizationId: 'org-novapulse-01',
    recipientUserId: 'user-003', // Ananya Sharma
    recipientEmployeeId: 'emp-003',
    title: 'New Candidate Onboarding Submitted',
    message: 'Akash Deep (Software Engineer II) has submitted self-service onboarding documents for HR verification.',
    type: 'onboarding',
    link: '/onboarding',
    isRead: false,
    createdAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'notif-003',
    organizationId: 'org-novapulse-01',
    recipientUserId: 'user-001',
    title: 'Biometric Cloud Gateway Active',
    message: 'Biometric terminals at Delhi HQ and Mumbai Hub synchronized 100% punch records with zero loss.',
    type: 'system',
    link: '/attendance',
    isRead: true,
    createdAt: '2026-09-21T09:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-001',
    organizationId: 'org-novapulse-01',
    userId: 'user-001',
    userName: 'Yatender Sharma',
    userRole: 'Super Admin',
    module: 'Employee Management',
    action: 'CREATE',
    description: 'Added new employee master profile: Sneha Kapoor (NP-1009)',
    recordId: 'emp-009',
    timestamp: '2026-09-18T10:15:00Z',
    ipAddress: '192.168.1.42',
  },
  {
    id: 'audit-002',
    organizationId: 'org-novapulse-01',
    userId: 'user-002',
    userName: 'Vikram Malhotra',
    userRole: 'Manager',
    module: 'Leave Management',
    action: 'APPROVE',
    description: 'Approved Sick Leave application (2 days) for Kunal Verma',
    recordId: 'la-002',
    timestamp: '2026-09-14T16:00:00Z',
    ipAddress: '192.168.1.88',
  },
  {
    id: 'audit-003',
    organizationId: 'org-novapulse-01',
    userId: 'user-006',
    userName: 'Pooja Iyer',
    userRole: 'Payroll Admin',
    module: 'Payroll Management',
    action: 'PROCESS',
    description: 'Finalized August 2026 Payroll Run & Disbursed Salary Slips for 10 Employees',
    recordId: 'pay-2026-08',
    timestamp: '2026-08-31T18:30:00Z',
    ipAddress: '192.168.1.105',
  },
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'NP-000001',
    tenantId: 'NP-000001',
    companyName: 'NovaPulse Technologies Pvt. Ltd.',
    legalName: 'NovaPulse Technologies Private Limited',
    email: 'contact@novapulse.co.in',
    phone: '+91 87966 23604',
    address: 'Plot 42, Sector 62, Electronic City',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    gstin: '07JTGPK2862G1ZF',
    industry: 'Information Technology & Software',
    logo: '/logo.png',
    clientCode: 'CLI-NP-01',
    slug: 'novapulse',
    subdomain: 'novapulse',
    loginSlug: 'https://novapulse.makemypayroll.com',
    status: 'ACTIVE',
    licensedEmployees: 50,
    subscriptionPlan: 'Enterprise Custom',
    subscriptionStartDate: '2026-01-01',
    subscriptionEndDate: '2027-12-31',
    paymentStatus: 'PAID',
    enabledModules: [
      'dashboard',
      'shifts',
      'attendance',
      'leaves',
      'employees',
      'tickets',
      'onboarding',
      'inventory',
      'geolocation',
      'payroll',
      'settings'
    ],
    primaryAdmin: {
      name: 'Yatender Sharma',
      email: 'yatender@novapulse.co.in',
      phone: '+91 98765 43210',
      userId: 'user-001'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-21T00:00:00Z'
  },
  {
    id: 'NP-000002',
    tenantId: 'NP-000002',
    companyName: 'Acme Global Manufacturing Pvt Ltd',
    legalName: 'Acme Global Manufacturing Private Limited',
    email: 'admin@acmeglobal.com',
    phone: '+91 98111 22334',
    address: 'Plot 108, Phase 2, Industrial Area',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    gstin: '06AACCA1234F1Z8',
    industry: 'Heavy Manufacturing & Automotive',
    logo: '/logo.png',
    clientCode: 'CLI-ACM-02',
    slug: 'acme',
    subdomain: 'acme',
    loginSlug: 'https://acme.makemypayroll.com',
    status: 'ACTIVE',
    licensedEmployees: 100,
    subscriptionPlan: 'Annual',
    subscriptionStartDate: '2026-03-01',
    subscriptionEndDate: '2027-02-28',
    paymentStatus: 'PAID',
    enabledModules: [
      'dashboard',
      'shifts',
      'attendance',
      'leaves',
      'employees',
      'tickets',
      'onboarding',
      'inventory',
      'geolocation',
      'payroll',
      'settings'
    ],
    primaryAdmin: {
      name: 'Rajesh Sharma',
      email: 'admin@acmeglobal.com',
      phone: '+91 98111 22334',
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-09-20T00:00:00Z'
  },
  {
    id: 'NP-000003',
    tenantId: 'NP-000003',
    companyName: 'Starlight Retail & Logistics',
    legalName: 'Starlight Retail Supermarkets Limited',
    email: 'admin@starlightretail.in',
    phone: '+91 99222 33445',
    address: 'Commercial Tower C, Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    gstin: '29AABCS9876Q1ZB',
    industry: 'Retail & Supply Chain',
    logo: '/logo.png',
    clientCode: 'CLI-STR-03',
    slug: 'starlight',
    subdomain: 'starlight',
    loginSlug: 'https://starlight.makemypayroll.com',
    status: 'ON_HOLD',
    licensedEmployees: 25,
    subscriptionPlan: 'Monthly',
    subscriptionStartDate: '2026-06-01',
    subscriptionEndDate: '2026-08-31',
    paymentStatus: 'OVERDUE',
    holdDetails: {
      heldAt: '2026-09-18T10:00:00Z',
      heldBy: 'Super Admin',
      reason: 'Subscription renewal payment overdue (>30 days). Awaiting wire transfer confirmation.'
    },
    enabledModules: [
      'dashboard',
      'attendance',
      'leaves',
      'employees',
      'payroll'
    ],
    primaryAdmin: {
      name: 'Vikram Malhotra',
      email: 'admin@starlightretail.in',
      phone: '+91 99222 33445'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z'
  },
  {
    id: 'NP-000004',
    tenantId: 'NP-000004',
    companyName: 'Zenith Healthcare Network',
    legalName: 'Zenith Multi-Speciality Hospitals & Diagnostics Pvt Ltd',
    email: 'contact@zenithhealth.org',
    phone: '+91 98444 55667',
    address: '88 Hospital Road, Vasant Kunj',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    gstin: '07AAACZ4321P1Z5',
    industry: 'Healthcare & Hospitals',
    logo: '/logo.png',
    clientCode: 'CLI-ZEN-04',
    slug: 'zenith',
    subdomain: 'zenith',
    loginSlug: 'https://zenith.makemypayroll.com',
    status: 'TRIAL',
    licensedEmployees: 150,
    subscriptionPlan: 'Trial',
    subscriptionStartDate: '2026-09-15',
    subscriptionEndDate: '2026-10-15',
    trialEndDate: '2026-10-15',
    paymentStatus: 'PENDING',
    enabledModules: [
      'dashboard',
      'shifts',
      'attendance',
      'leaves',
      'employees',
      'tickets',
      'onboarding',
      'settings'
    ],
    primaryAdmin: {
      name: 'Dr. Ananya Sen',
      email: 'ananya@zenithhealth.org',
      phone: '+91 98444 55667'
    },
    setupCompleted: false,
    setupStep: 6,
    createdAt: '2026-09-15T00:00:00Z',
    updatedAt: '2026-09-22T00:00:00Z'
  },
  {
    id: 'NP-000005',
    tenantId: 'NP-000005',
    companyName: 'Quantum Fintech Solutions',
    legalName: 'Quantum FinTech Services LLP',
    email: 'accounts@quantumfintech.io',
    phone: '+91 97555 66778',
    address: 'Cyber Hub Tower 4, DLF Phase 3',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    gstin: '06AABFQ5678R1ZX',
    industry: 'Financial Technology & Banking',
    logo: '/logo.png',
    clientCode: 'CLI-QNT-05',
    slug: 'quantum',
    subdomain: 'quantum',
    loginSlug: 'https://quantum.makemypayroll.com',
    status: 'SUSPENDED',
    licensedEmployees: 50,
    subscriptionPlan: 'Quarterly',
    subscriptionStartDate: '2026-05-01',
    subscriptionEndDate: '2026-08-01',
    paymentStatus: 'OVERDUE',
    holdDetails: {
      heldAt: '2026-08-15T09:00:00Z',
      heldBy: 'Super Admin',
      reason: 'Terms of service violation and payment default.'
    },
    enabledModules: [
      'dashboard',
      'attendance',
      'leaves',
      'employees'
    ],
    primaryAdmin: {
      name: 'Rohan Mehra',
      email: 'rohan@quantumfintech.io',
      phone: '+91 97555 66778'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z'
  },
  {
    id: 'NP-000006',
    tenantId: 'NP-000006',
    companyName: 'Silaris Information Technologies',
    legalName: 'Silaris Information Technologies Private Limited',
    email: 'admin@silaris.in',
    phone: '+91 98111 55667',
    address: 'A-24/5, Mohan Cooperative Industrial Estate, Mathura Road',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    gstin: '07AAACS5678Q1Z2',
    industry: 'Information Technology & BPO',
    logo: '/logo.png',
    clientCode: 'CLI-SIL-06',
    slug: 'silaris',
    subdomain: 'silaris',
    loginSlug: 'https://silaris.makemypayroll.com',
    status: 'ACTIVE',
    licensedEmployees: 50,
    subscriptionPlan: 'Annual',
    subscriptionStartDate: '2026-09-24',
    subscriptionEndDate: '2027-09-23',
    paymentStatus: 'PAID',
    enabledModules: [
      'dashboard',
      'shifts',
      'attendance',
      'leaves',
      'employees',
      'tickets',
      'onboarding',
      'inventory',
      'geolocation',
      'payroll',
      'settings'
    ],
    primaryAdmin: {
      name: 'Yatender Sharma',
      email: 'yatender@novapulse.co.in',
      phone: '+91 87966 23604',
      userId: 'user-001'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-09-24T10:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z'
  },
  {
    id: 'NP-000007',
    tenantId: 'NP-000007',
    companyName: 'Ignite Technologies Pvt Ltd',
    legalName: 'Ignite Technologies Private Limited',
    email: 'admin@ignite.co.in',
    phone: '+91 98111 00111',
    address: 'Tech Park, Cyber Hub',
    city: 'Gurugram',
    state: 'Haryana',
    country: 'India',
    gstin: '06AACCI1122Q1Z3',
    industry: 'Cloud Solutions & Consulting',
    logo: '/logo.png',
    clientCode: 'CLI-IGN-07',
    slug: 'ignite',
    subdomain: 'ignite',
    loginSlug: 'https://ignite.makemypayroll.com',
    status: 'ACTIVE',
    licensedEmployees: 50,
    subscriptionPlan: 'Enterprise Custom',
    subscriptionStartDate: '2026-01-01',
    subscriptionEndDate: '2027-12-31',
    paymentStatus: 'PAID',
    primaryAdmin: {
      name: 'Rahul Sharma',
      email: 'admin@ignitecompany.com',
      phone: '+91 98111 00111'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z'
  },
  {
    id: 'NP-000008',
    tenantId: 'NP-000008',
    companyName: 'Razor Infotech Pvt Ltd',
    legalName: 'Razor Infotech Private Limited',
    email: 'admin@razor.in',
    phone: '+91 98222 00222',
    address: 'Commercial Tower A, Sector 18',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    gstin: '07AAACR3344R1Z5',
    industry: 'Software Development',
    logo: '/logo.png',
    clientCode: 'CLI-RAZ-08',
    slug: 'razor',
    subdomain: 'razor',
    loginSlug: 'https://razor.makemypayroll.com',
    status: 'ACTIVE',
    licensedEmployees: 50,
    subscriptionPlan: 'Annual',
    subscriptionStartDate: '2026-01-01',
    subscriptionEndDate: '2027-12-31',
    paymentStatus: 'PAID',
    primaryAdmin: {
      name: 'Amit Patel',
      email: 'admin@razor.in',
      phone: '+91 98222 00222'
    },
    setupCompleted: true,
    setupStep: 10,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z'
  }
];

export const INITIAL_TENANT_SUBSCRIPTIONS: TenantSubscription[] = [
  {
    id: 'sub-001',
    tenantId: 'NP-000001',
    companyName: 'NovaPulse Technologies Pvt. Ltd.',
    planName: 'Enterprise Custom',
    billingCycle: 'Annual',
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    licensedEmployees: 50,
    amount: 0,
    currency: 'INR',
    paymentStatus: 'PAID',
    renewalDate: '2027-12-31',
    paymentReference: 'INTERNAL-CORP-01',
    notes: 'Internal primary production instance',
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'sub-002',
    tenantId: 'NP-000002',
    companyName: 'Acme Global Manufacturing Pvt Ltd',
    planName: 'Annual',
    billingCycle: 'Annual',
    startDate: '2026-03-01',
    endDate: '2027-02-28',
    licensedEmployees: 100,
    amount: 144000,
    currency: 'INR',
    paymentStatus: 'PAID',
    renewalDate: '2027-02-28',
    paymentReference: 'TXN-HDFC-99281',
    notes: 'Prepaid Annual Enterprise Pack (₹120/employee/month)',
    createdAt: '2026-03-01T00:00:00Z'
  },
  {
    id: 'sub-003',
    tenantId: 'NP-000003',
    companyName: 'Starlight Retail & Logistics',
    planName: 'Monthly',
    billingCycle: 'Monthly',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    licensedEmployees: 25,
    amount: 3750,
    currency: 'INR',
    paymentStatus: 'OVERDUE',
    renewalDate: '2026-09-01',
    paymentReference: 'INV-2026-09-003',
    notes: 'Monthly billing cycle. Invoice overdue by 23 days.',
    createdAt: '2026-06-01T00:00:00Z'
  },
  {
    id: 'sub-004',
    tenantId: 'NP-000004',
    companyName: 'Zenith Healthcare Network',
    planName: 'Trial',
    billingCycle: 'Monthly',
    startDate: '2026-09-15',
    endDate: '2026-10-15',
    licensedEmployees: 150,
    amount: 0,
    currency: 'INR',
    paymentStatus: 'PENDING',
    renewalDate: '2026-10-15',
    notes: '30-Day Full Feature Enterprise Trial Pilot',
    createdAt: '2026-09-15T00:00:00Z'
  },
  {
    id: 'sub-005',
    tenantId: 'NP-000005',
    companyName: 'Quantum Fintech Solutions',
    planName: 'Quarterly',
    billingCycle: 'Quarterly',
    startDate: '2026-05-01',
    endDate: '2026-08-01',
    licensedEmployees: 50,
    amount: 22500,
    currency: 'INR',
    paymentStatus: 'OVERDUE',
    renewalDate: '2026-08-01',
    notes: 'Quarterly subscription expired without renewal.',
    createdAt: '2026-05-01T00:00:00Z'
  },
  {
    id: 'sub-006',
    tenantId: 'NP-000006',
    companyName: 'Silaris Information Technologies Pvt Ltd',
    planName: 'Annual',
    billingCycle: 'Annual',
    startDate: '2026-09-24',
    endDate: '2027-09-23',
    licensedEmployees: 50,
    amount: 72000,
    currency: 'INR',
    paymentStatus: 'PAID',
    renewalDate: '2027-09-23',
    paymentReference: 'TXN-SILARIS-2026',
    notes: 'Annual Enterprise Plan for Silaris',
    createdAt: '2026-09-24T10:00:00Z'
  },
  {
    id: 'sub-007',
    tenantId: 'NP-000007',
    companyName: 'Ignite Technologies Pvt Ltd',
    planName: 'Enterprise Custom',
    billingCycle: 'Annual',
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    licensedEmployees: 50,
    amount: 72000,
    currency: 'INR',
    paymentStatus: 'PAID',
    renewalDate: '2027-12-31',
    paymentReference: 'TXN-IGNITE-2026',
    notes: 'Annual Enterprise Plan for Ignite',
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'sub-008',
    tenantId: 'NP-000008',
    companyName: 'Razor Infotech Pvt Ltd',
    planName: 'Annual',
    billingCycle: 'Annual',
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    licensedEmployees: 50,
    amount: 72000,
    currency: 'INR',
    paymentStatus: 'PAID',
    renewalDate: '2027-12-31',
    paymentReference: 'TXN-RAZOR-2026',
    notes: 'Annual Enterprise Plan for Razor',
    createdAt: '2026-01-01T00:00:00Z'
  }
];

export const INITIAL_TENANT_LICENSE_CHANGES: TenantLicenseChange[] = [
  {
    id: 'lic-chg-001',
    tenantId: 'NP-000002',
    companyName: 'Acme Global Manufacturing Pvt Ltd',
    previousLimit: 50,
    newLimit: 100,
    changedBy: 'Super Admin (Yatender Sharma)',
    reason: 'Upgraded to Annual Enterprise 100-pack for plant expansion',
    timestamp: '2026-05-10T14:30:00Z'
  },
  {
    id: 'lic-chg-002',
    tenantId: 'NP-000001',
    companyName: 'NovaPulse Technologies Pvt. Ltd.',
    previousLimit: 20,
    newLimit: 50,
    changedBy: 'Super Admin',
    reason: 'Internal capacity enhancement',
    timestamp: '2026-04-01T10:00:00Z'
  }
];

export const INITIAL_TENANT_PAYMENTS: TenantPayment[] = [
  {
    id: 'pay-inv-001',
    invoiceNumber: 'INV-NP-2026-001',
    tenantId: 'NP-000002',
    companyName: 'Acme Global Manufacturing Pvt Ltd',
    plan: 'Annual Enterprise (100 Licences)',
    amount: 144000,
    taxAmount: 25920,
    totalAmount: 169920,
    paymentDate: '2026-03-01',
    dueDate: '2026-03-10',
    status: 'PAID',
    paymentMethod: 'NEFT / Wire Transfer',
    transactionId: 'HDFC-N99281-2026',
    createdAt: '2026-03-01T00:00:00Z'
  },
  {
    id: 'pay-inv-002',
    invoiceNumber: 'INV-NP-2026-002',
    tenantId: 'NP-000003',
    companyName: 'Starlight Retail & Logistics',
    plan: 'Monthly Regular (25 Licences)',
    amount: 3750,
    taxAmount: 675,
    totalAmount: 4425,
    paymentDate: '',
    dueDate: '2026-09-05',
    status: 'OVERDUE',
    paymentMethod: 'Corporate Net Banking',
    createdAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'pay-inv-003',
    invoiceNumber: 'INV-NP-2026-003',
    tenantId: 'NP-000005',
    companyName: 'Quantum Fintech Solutions',
    plan: 'Quarterly Pack (50 Licences)',
    amount: 22500,
    taxAmount: 4050,
    totalAmount: 26550,
    paymentDate: '',
    dueDate: '2026-08-05',
    status: 'OVERDUE',
    paymentMethod: 'UPI / Card',
    createdAt: '2026-08-01T00:00:00Z'
  }
];

export const INITIAL_PAYROLL_CYCLES: PayrollCycle[] = [
  {
    id: 'cycle-001',
    organizationId: 'NP-000001',
    name: 'Monthly Standard (1st to 30th/31st)',
    startDay: 1,
    endDay: 31,
    isDefault: true,
    status: 'Active',
    description: 'Standard calendar month payroll cycle from 1st day to last day of the month.',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cycle-002',
    organizationId: 'NP-000001',
    name: 'Mid-Month Cycle (20th to 19th)',
    startDay: 20,
    endDay: 19,
    isDefault: false,
    status: 'Active',
    description: 'Mid-month attendance cutoff cycle running from 20th of previous month to 19th of current month.',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'cycle-003',
    organizationId: 'NP-000001',
    name: 'Factory & Operations Cut-Off (26th to 25th)',
    startDay: 26,
    endDay: 25,
    isDefault: false,
    status: 'Active',
    description: 'Factory and plant workforce cycle from 26th of previous month to 25th of current month.',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_ATTENDANCE_POLICIES: AttendancePolicy[] = [
  {
    id: 'pol-001',
    organizationId: 'NP-000001',
    name: 'Standard Corporate Policy',
    description: 'Corporate headquarters policy with standard 8-hour workday, 15-minute grace period, and overtime benefits.',
    isDefault: true,
    status: 'Active',
    fullDayHours: 8.0,
    halfDayHours: 4.5,
    fullDayCreditToleranceMinutes: 15,
    minimumOtHoursDaily: 1.0,
    otPunchGapSeconds: 60,
    maxLeaveCarryoverDays: 10,
    enableOvertime: true,
    overtimePayScale: 1.5,
    countOutsideShiftHours: false,
    salesProductivityAttendance: false,
    otDetectionEnabled: true,
    otDetectionMode: 'after_shift',
    otWindowMinutes: 30,
    dailyLateAllowanceMinutes: 15,
    lateComingGraceMinutes: 15,
    maxMonthlyLatenessAllowed: 3,
    latePenaltyType: 'HalfDay',
    latePenaltyValue: 0.5,
    fullDayCreditLogic: 'inside_shift_only',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'pol-002',
    organizationId: 'NP-000001',
    name: 'Factory & Operations Staff Policy',
    description: 'Plant and factory attendance rules with strict punctuality, 9-hour shifts, and double overtime pay.',
    isDefault: false,
    status: 'Active',
    fullDayHours: 9.0,
    halfDayHours: 5.0,
    fullDayCreditToleranceMinutes: 10,
    minimumOtHoursDaily: 1.0,
    otPunchGapSeconds: 30,
    maxLeaveCarryoverDays: 15,
    enableOvertime: true,
    overtimePayScale: 2.0,
    countOutsideShiftHours: true,
    salesProductivityAttendance: false,
    otDetectionEnabled: true,
    otDetectionMode: 'both',
    otWindowMinutes: 60,
    dailyLateAllowanceMinutes: 10,
    lateComingGraceMinutes: 10,
    maxMonthlyLatenessAllowed: 2,
    latePenaltyType: 'Deduction',
    latePenaltyValue: 500,
    fullDayCreditLogic: 'inside_shift_only',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'pol-003',
    organizationId: 'NP-000001',
    name: 'Sales & Field Team Policy',
    description: 'Flexible attendance policy for field executives and traveling sales teams with relaxed grace periods.',
    isDefault: false,
    status: 'Active',
    fullDayHours: 8.0,
    halfDayHours: 4.0,
    fullDayCreditToleranceMinutes: 30,
    minimumOtHoursDaily: 2.0,
    otPunchGapSeconds: 60,
    maxLeaveCarryoverDays: 8,
    enableOvertime: false,
    overtimePayScale: 1.0,
    countOutsideShiftHours: false,
    salesProductivityAttendance: true,
    otDetectionEnabled: false,
    otDetectionMode: 'after_shift',
    otWindowMinutes: 30,
    dailyLateAllowanceMinutes: 30,
    lateComingGraceMinutes: 30,
    maxMonthlyLatenessAllowed: 5,
    latePenaltyType: 'Warning',
    latePenaltyValue: 0,
    fullDayCreditLogic: 'can_stay_late',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_OVERTIME_CONFIGS: OvertimeConfig[] = [
  {
    id: 'ot-config-001',
    organizationId: 'NP-000001',
    isEnabled: true,
    calculationMethod: 'MULTIPLIER',
    multiplier: 1.5,
    fixedAmountPerHour: 200,
    fixedAmountPerDay: 1500,
    minOtHoursDaily: 0.5,
    otRoundingMinutes: 15,
    detectionMode: 'after_shift',
    requireApproval: false,
    maxDailyOtHours: 4,
    maxMonthlyOtHours: 40,
    updatedAt: '2026-04-01T00:00:00Z',
  },
];

export const INITIAL_SALARY_COMPONENTS: SalaryComponent[] = [
  {
    id: 'comp-001',
    organizationId: 'NP-000001',
    name: 'Performance Incentive',
    componentType: 'Incentive',
    calculationMethod: 'FIXED',
    value: 5000,
    isRecurring: true,
    isTaxable: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    payslipDisplayName: 'Performance Incentive',
    status: 'Active',
    description: 'Monthly performance-linked variable incentive',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'comp-002',
    organizationId: 'NP-000001',
    name: 'Travel & Field Allowance',
    componentType: 'Allowance',
    calculationMethod: 'FIXED',
    value: 3000,
    isRecurring: true,
    isTaxable: false,
    isPfApplicable: false,
    isEsiApplicable: false,
    payslipDisplayName: 'Travel Allowance',
    status: 'Active',
    description: 'Conveyance allowance for local and client visits',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'comp-003',
    organizationId: 'NP-000001',
    name: 'Night Shift Allowance',
    componentType: 'Allowance',
    calculationMethod: 'FIXED',
    value: 2500,
    isRecurring: true,
    isTaxable: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    payslipDisplayName: 'Shift Allowance',
    status: 'Active',
    description: 'Special allowance for night shifts and weekend roster',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'comp-004',
    organizationId: 'NP-000001',
    name: 'Festive Bonus',
    componentType: 'Bonus',
    calculationMethod: 'PERCENT_BASIC',
    value: 10,
    isRecurring: false,
    isTaxable: true,
    isPfApplicable: false,
    isEsiApplicable: false,
    payslipDisplayName: 'Festive Bonus',
    status: 'Active',
    description: '10% of basic salary festive bonus during designated months',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const INITIAL_DEDUCTION_POLICIES: DeductionPolicy[] = [
  {
    id: 'ded-001',
    organizationId: 'NP-000001',
    name: 'Late Coming Penalty Deduction',
    deductionType: 'Late Coming Penalty',
    calculationMethod: 'FIXED',
    value: 100,
    isRecurring: true,
    isTaxDeductible: false,
    isAutomatic: true,
    status: 'Active',
    description: 'Automatic deduction per excess unexcused late occurrence',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ded-002',
    organizationId: 'NP-000001',
    name: 'Asset Damage / Loss Recovery',
    deductionType: 'Damage/Recovery',
    calculationMethod: 'FIXED',
    value: 500,
    isRecurring: false,
    isTaxDeductible: false,
    isAutomatic: false,
    status: 'Active',
    description: 'Recovery for damaged or lost company assets',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'ded-003',
    organizationId: 'NP-000001',
    name: 'Unpaid Leave (LOP) Deduction',
    deductionType: 'Unpaid Leave Deduction',
    calculationMethod: 'DAYS_LOP',
    value: 1.0,
    isRecurring: true,
    isTaxDeductible: false,
    isAutomatic: true,
    status: 'Active',
    description: 'Pro-rata salary deduction for unauthorized absenteeism and unpaid leave days',
    createdBy: 'Super Admin',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// ====================================================================
// INITIAL TASK MANAGEMENT & TEAM PROJECTS SEED DATA
// ====================================================================

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'tsk-001',
    taskCode: 'TSK-1001',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    title: 'Deploy Production Hotfix for Multi-Tenant SSO Routing',
    description: 'Resolve edge-case SSL certificate and subdomain header propagation for dedicated tenant vanity URLs.',
    assignedById: 'emp-001',
    assignedByName: 'Yatender Sharma',
    assignedToId: 'emp-002',
    assignedToName: 'Vikram Malhotra',
    assignedToAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    departmentId: 'dept-eng-01',
    departmentName: 'Engineering & Technology',
    designationId: 'desig-01',
    designationTitle: 'VP of Engineering',
    priority: 'Urgent',
    category: 'Development',
    startDate: '2026-09-28',
    dueDate: '2026-10-05',
    status: 'In Progress',
    progress: 75,
    subtasks: [
      { id: 'sub-101', taskId: 'tsk-001', title: 'Audit SSL wildcard cert chain on ingress controller', isCompleted: true, completedAt: '2026-09-28T14:00:00Z', completedBy: 'Vikram Malhotra' },
      { id: 'sub-102', taskId: 'tsk-001', title: 'Patch TenantResolver middleware for custom domain propagation', isCompleted: true, completedAt: '2026-09-29T10:30:00Z', completedBy: 'Vikram Malhotra' },
      { id: 'sub-103', taskId: 'tsk-001', title: 'Verify on staging environment (*.makemypayroll.com)', isCompleted: true, completedAt: '2026-09-29T14:15:00Z', completedBy: 'Vikram Malhotra' },
      { id: 'sub-104', taskId: 'tsk-001', title: 'Deploy Canary build to production cluster', isCompleted: false },
    ],
    attachments: [
      { id: 'att-101', name: 'SSO_Routing_Architecture.pdf', url: '/docs/sso.pdf', size: '2.4 MB', uploadDate: '2026-09-28' },
    ],
    additionalInstructions: 'Ensure staging verification before pushing to production edge clusters.',
    comments: [
      {
        id: 'tc-001',
        taskId: 'tsk-001',
        authorId: 'emp-001',
        authorName: 'Yatender Sharma',
        authorRole: 'CEO / Super Admin',
        departmentName: 'Management',
        content: 'Please prioritize this before the Q4 client onboarding cycle kicks off.',
        createdAt: '2026-09-28T10:30:00Z',
      },
      {
        id: 'tc-002',
        taskId: 'tsk-001',
        authorId: 'emp-002',
        authorName: 'Vikram Malhotra',
        authorRole: 'VP of Engineering',
        departmentName: 'Engineering & Technology',
        content: 'Staging ingress controller updated and verified. Preparing Canary deployment.',
        createdAt: '2026-09-29T14:15:00Z',
      },
    ],
    activities: [
      { id: 'act-001', taskId: 'tsk-001', userId: 'user-001', userName: 'Yatender Sharma', action: 'Created Task', timestamp: '2026-09-28T09:00:00Z' },
      { id: 'act-002', taskId: 'tsk-001', userId: 'user-002', userName: 'Vikram Malhotra', action: 'Updated Progress to 75%', timestamp: '2026-09-29T14:15:00Z' },
    ],
    createdAt: '2026-09-28T09:00:00Z',
    updatedAt: '2026-09-29T14:15:00Z',
  },
  {
    id: 'tsk-002',
    taskCode: 'TSK-1002',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    title: 'Verify Statutory PF & ESI Filings for September 2026',
    description: 'Cross-check monthly ECR submission report with attendance muster and salary register before filing on EPFO portal.',
    assignedById: 'emp-001',
    assignedByName: 'Yatender Sharma',
    assignedToId: 'emp-006',
    assignedToName: 'Pooja Iyer',
    assignedToAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    departmentId: 'dept-finance-05',
    departmentName: 'Finance & Payroll Operations',
    designationId: 'desig-07',
    designationTitle: 'Finance & Accounts Lead',
    priority: 'High',
    category: 'Finance',
    startDate: '2026-10-01',
    dueDate: '2026-10-10',
    status: 'In Progress',
    progress: 40,
    subtasks: [
      { id: 'sub-201', taskId: 'tsk-002', title: 'Export monthly attendance & LOP muster', isCompleted: true, completedAt: '2026-10-01T11:00:00Z', completedBy: 'Pooja Iyer' },
      { id: 'sub-202', taskId: 'tsk-002', title: 'Generate PF ECR text file from payroll register', isCompleted: true, completedAt: '2026-10-01T15:30:00Z', completedBy: 'Pooja Iyer' },
      { id: 'sub-203', taskId: 'tsk-002', title: 'Validate challan computation with EPFO portal schema', isCompleted: false },
      { id: 'sub-204', taskId: 'tsk-002', title: 'Submit payment and archive bank TRRN receipt', isCompleted: false },
    ],
    attachments: [
      { id: 'att-102', name: 'ECR_Sept_Summary.xlsx', url: '/docs/ecr.xlsx', size: '1.1 MB', uploadDate: '2026-10-01' },
    ],
    comments: [
      {
        id: 'tc-003',
        taskId: 'tsk-002',
        authorId: 'emp-006',
        authorName: 'Pooja Iyer',
        authorRole: 'Finance Head',
        departmentName: 'Finance & Payroll Operations',
        content: 'Draft ECR text file generated. Reconciling 2 employee LOP adjustments.',
        createdAt: '2026-10-01T16:00:00Z',
      },
    ],
    activities: [
      { id: 'act-003', taskId: 'tsk-002', userId: 'user-001', userName: 'Yatender Sharma', action: 'Created Task', timestamp: '2026-10-01T09:30:00Z' },
    ],
    createdAt: '2026-10-01T09:30:00Z',
    updatedAt: '2026-10-01T16:00:00Z',
  },
  {
    id: 'tsk-003',
    taskCode: 'TSK-1003',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    title: 'Complete Background Verification for Q4 Engineering Hires',
    description: 'Collect education verification transcripts and past employer relieving letters for candidate cohort #2026-Q4.',
    assignedById: 'emp-003',
    assignedByName: 'Ananya Sharma',
    assignedToId: 'emp-008',
    assignedToName: 'Priya Patel',
    assignedToAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    departmentId: 'dept-hr-02',
    departmentName: 'Human Resources & People Ops',
    designationId: 'desig-09',
    designationTitle: 'HR Business Partner',
    priority: 'Medium',
    category: 'HR',
    startDate: '2026-09-25',
    dueDate: '2026-10-08',
    status: 'In Progress',
    progress: 60,
    subtasks: [
      { id: 'sub-301', taskId: 'tsk-003', title: 'Collect Aadhaar & PAN identity documents', isCompleted: true, completedAt: '2026-09-26T10:00:00Z', completedBy: 'Priya Patel' },
      { id: 'sub-302', taskId: 'tsk-003', title: 'Initiate university degree transcript verification', isCompleted: true, completedAt: '2026-09-27T12:00:00Z', completedBy: 'Priya Patel' },
      { id: 'sub-303', taskId: 'tsk-003', title: 'Validate previous employer experience certificates', isCompleted: true, completedAt: '2026-09-29T16:00:00Z', completedBy: 'Priya Patel' },
      { id: 'sub-304', taskId: 'tsk-003', title: 'Generate final BGV clearance certificate', isCompleted: false },
    ],
    attachments: [],
    comments: [],
    activities: [
      { id: 'act-004', taskId: 'tsk-003', userId: 'user-003', userName: 'Ananya Sharma', action: 'Created Task', timestamp: '2026-09-25T11:00:00Z' },
    ],
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-25T11:00:00Z',
  },
  {
    id: 'tsk-004',
    taskCode: 'TSK-1004',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    title: 'Quarterly Workplace Asset & Laptop Audit',
    description: 'Verify serial numbers, condition tags, and warranty certificates for all deployed assets across Delhi & Mumbai offices.',
    assignedById: 'emp-005',
    assignedByName: 'Kunal Verma',
    assignedToId: 'emp-005',
    assignedToName: 'Kunal Verma',
    assignedToAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    departmentId: 'dept-it-04',
    departmentName: 'IT & Workplace Security',
    designationId: 'desig-08',
    designationTitle: 'IT Infrastructure Head',
    priority: 'Low',
    category: 'Operations',
    startDate: '2026-09-15',
    dueDate: '2026-09-30',
    status: 'Completed',
    progress: 100,
    subtasks: [
      { id: 'sub-401', taskId: 'tsk-004', title: 'Scan barcode and MAC addresses of 48 laptops', isCompleted: true, completedAt: '2026-09-20T17:00:00Z', completedBy: 'Kunal Verma' },
      { id: 'sub-402', taskId: 'tsk-004', title: 'Verify MDM security policy compliance', isCompleted: true, completedAt: '2026-09-25T15:00:00Z', completedBy: 'Kunal Verma' },
      { id: 'sub-403', taskId: 'tsk-004', title: 'Generate asset health audit report', isCompleted: true, completedAt: '2026-09-30T17:00:00Z', completedBy: 'Kunal Verma' },
    ],
    completedAt: '2026-09-30T17:00:00Z',
    attachments: [],
    comments: [
      {
        id: 'tc-004',
        taskId: 'tsk-004',
        authorId: 'emp-005',
        authorName: 'Kunal Verma',
        authorRole: 'IT Head',
        departmentName: 'IT & Workplace Security',
        content: 'All 48 office laptops verified. 2 battery replacements scheduled.',
        createdAt: '2026-09-30T17:00:00Z',
      },
    ],
    activities: [
      { id: 'act-005', taskId: 'tsk-004', userId: 'user-005', userName: 'Kunal Verma', action: 'Marked Completed', timestamp: '2026-09-30T17:00:00Z' },
    ],
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-30T17:00:00Z',
  },
  {
    id: 'tsk-005',
    taskCode: 'TSK-1005',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    title: 'Prepare Renewal Quotations for Silaris Tech Account',
    description: 'Generate commercial contract annexure with revised user licensing tiers and support SLA clauses.',
    assignedById: 'emp-004',
    assignedByName: 'Rajesh Nair',
    assignedToId: 'emp-004',
    assignedToName: 'Rajesh Nair',
    assignedToAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    departmentId: 'dept-sales-03',
    departmentName: 'Sales & Business Growth',
    designationId: 'desig-10',
    designationTitle: 'Senior Account Executive',
    priority: 'High',
    category: 'Sales',
    startDate: '2026-09-20',
    dueDate: '2026-09-29',
    status: 'Overdue',
    progress: 30,
    subtasks: [
      { id: 'sub-501', taskId: 'tsk-005', title: 'Review license count usage in Silaris tenant', isCompleted: true, completedAt: '2026-09-22T11:00:00Z', completedBy: 'Rajesh Nair' },
      { id: 'sub-502', taskId: 'tsk-005', title: 'Draft revised rate proposal for 50 employee tier', isCompleted: false },
      { id: 'sub-503', taskId: 'tsk-005', title: 'Obtain CEO commercial approval', isCompleted: false },
    ],
    attachments: [],
    comments: [],
    activities: [
      { id: 'act-006', taskId: 'tsk-005', userId: 'user-004', userName: 'Rajesh Nair', action: 'Created Task', timestamp: '2026-09-20T12:00:00Z' },
    ],
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },
];

export const INITIAL_PROJECTS: TeamProject[] = [
  {
    id: 'prj-001',
    projectCode: 'PRJ-1001',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    name: 'Enterprise Client Onboarding & Billing Setup',
    description: 'End-to-end sequential customer launch pipeline spanning sales signoff, HR background verifications, billing configuration, operational onboarding, and IT provisioning.',
    client: 'Reliance Digital Enterprise',
    ownerEmployeeId: 'emp-001',
    ownerName: 'Yatender Sharma',
    priority: 'Urgent',
    startDate: '2026-09-15',
    targetDate: '2026-10-25',
    status: 'In Progress',
    currentDepartmentId: 'dept-finance-05',
    currentDepartmentName: 'Finance & Payroll Operations',
    currentStageIndex: 2, // 0=Sales, 1=HR, 2=Finance (Active), 3=Ops, 4=IT
    stages: [
      {
        id: 'stg-001',
        projectId: 'prj-001',
        departmentId: 'dept-sales-03',
        departmentName: 'Sales & Business Growth',
        departmentColor: '#10b981',
        sequence: 1,
        assignedEmployeeId: 'emp-004',
        assignedEmployeeName: 'Rajesh Nair',
        status: 'Completed',
        startDate: '2026-09-15',
        dueDate: '2026-09-20',
        completedDate: '2026-09-19',
        progress: 100,
        submissionNotes: 'Commercial terms finalized and master services agreement signed by client stakeholders.',
        attachments: [{ id: 'pa-01', name: 'Signed_MSA_Contract.pdf', url: '/docs/msa.pdf', uploadDate: '2026-09-19' }],
      },
      {
        id: 'stg-002',
        projectId: 'prj-001',
        departmentId: 'dept-hr-02',
        departmentName: 'Human Resources & People Ops',
        departmentColor: '#8b5cf6',
        sequence: 2,
        assignedEmployeeId: 'emp-003',
        assignedEmployeeName: 'Ananya Sharma',
        status: 'Completed',
        startDate: '2026-09-20',
        dueDate: '2026-09-27',
        completedDate: '2026-09-26',
        progress: 100,
        submissionNotes: 'Dedicated team allocation complete. Compliance documents and KYC verified.',
        attachments: [{ id: 'pa-02', name: 'Team_Staffing_Roster.xlsx', url: '/docs/roster.xlsx', uploadDate: '2026-09-26' }],
      },
      {
        id: 'stg-003',
        projectId: 'prj-001',
        departmentId: 'dept-finance-05',
        departmentName: 'Finance & Payroll Operations',
        departmentColor: '#ec4899',
        sequence: 3,
        assignedEmployeeId: 'emp-006',
        assignedEmployeeName: 'Pooja Iyer',
        status: 'Active',
        startDate: '2026-09-27',
        dueDate: '2026-10-06',
        progress: 65,
        submissionNotes: '',
        attachments: [],
      },
      {
        id: 'stg-004',
        projectId: 'prj-001',
        departmentId: 'dept-ops-06',
        departmentName: 'Customer Success & Ops',
        departmentColor: '#06b6d4',
        sequence: 4,
        assignedEmployeeId: 'emp-007',
        assignedEmployeeName: 'Amit Saxena',
        status: 'Locked',
        dueDate: '2026-10-15',
        progress: 0,
      },
      {
        id: 'stg-005',
        projectId: 'prj-001',
        departmentId: 'dept-it-04',
        departmentName: 'IT & Workplace Security',
        departmentColor: '#f59e0b',
        sequence: 5,
        assignedEmployeeId: 'emp-005',
        assignedEmployeeName: 'Kunal Verma',
        status: 'Locked',
        dueDate: '2026-10-25',
        progress: 0,
      },
    ],
    attachments: [
      { id: 'pa-01', name: 'Signed_MSA_Contract.pdf', url: '/docs/msa.pdf', uploadDate: '2026-09-19' },
      { id: 'pa-02', name: 'Team_Staffing_Roster.xlsx', url: '/docs/roster.xlsx', uploadDate: '2026-09-26' },
    ],
    comments: [
      {
        id: 'pc-001',
        projectId: 'prj-001',
        authorId: 'emp-004',
        authorName: 'Rajesh Nair',
        departmentName: 'Sales & Business Growth',
        content: 'Client requested kickoff by October 25th. Moving swiftly through finance approval.',
        createdAt: '2026-09-19T15:00:00Z',
      },
      {
        id: 'pc-002',
        projectId: 'prj-001',
        authorId: 'emp-006',
        authorName: 'Pooja Iyer',
        departmentName: 'Finance & Payroll Operations',
        content: 'GSTIN validation completed. Setting up automated debit and monthly invoicing structure.',
        createdAt: '2026-09-28T11:20:00Z',
      },
    ],
    activities: [
      { id: 'pact-001', projectId: 'prj-001', userId: 'user-001', userName: 'Yatender Sharma', action: 'Created Project', timestamp: '2026-09-15T09:00:00Z' },
      { id: 'pact-002', projectId: 'prj-001', userId: 'user-004', userName: 'Rajesh Nair', departmentName: 'Sales', action: 'Submitted Stage 1 (Sales) to HR', timestamp: '2026-09-19T16:30:00Z' },
      { id: 'pact-003', projectId: 'prj-001', userId: 'user-003', userName: 'Ananya Sharma', departmentName: 'HR', action: 'Submitted Stage 2 (HR) to Finance', timestamp: '2026-09-26T17:00:00Z' },
    ],
    createdAt: '2026-09-15T09:00:00Z',
    updatedAt: '2026-09-28T11:20:00Z',
  },
  {
    id: 'prj-002',
    projectCode: 'PRJ-1002',
    organizationId: 'NP-000001',
    tenantId: 'NP-000001',
    name: 'Quarterly SOC2 & ISO 27001 Compliance Audit',
    description: 'System security audit, access review, log integrity verification, and employee compliance signoff.',
    client: 'Internal Corporate Governance',
    ownerEmployeeId: 'emp-005',
    ownerName: 'Kunal Verma',
    priority: 'High',
    startDate: '2026-09-20',
    targetDate: '2026-10-30',
    status: 'In Progress',
    currentDepartmentId: 'dept-it-04',
    currentDepartmentName: 'IT & Workplace Security',
    currentStageIndex: 0,
    stages: [
      {
        id: 'stg-201',
        projectId: 'prj-002',
        departmentId: 'dept-it-04',
        departmentName: 'IT & Workplace Security',
        departmentColor: '#f59e0b',
        sequence: 1,
        assignedEmployeeId: 'emp-005',
        assignedEmployeeName: 'Kunal Verma',
        status: 'Active',
        startDate: '2026-09-20',
        dueDate: '2026-10-05',
        progress: 80,
      },
      {
        id: 'stg-202',
        projectId: 'prj-002',
        departmentId: 'dept-eng-01',
        departmentName: 'Engineering & Technology',
        departmentColor: '#3b82f6',
        sequence: 2,
        assignedEmployeeId: 'emp-002',
        assignedEmployeeName: 'Vikram Malhotra',
        status: 'Locked',
        dueDate: '2026-10-15',
        progress: 0,
      },
      {
        id: 'stg-203',
        projectId: 'prj-002',
        departmentId: 'dept-hr-02',
        departmentName: 'Human Resources & People Ops',
        departmentColor: '#8b5cf6',
        sequence: 3,
        assignedEmployeeId: 'emp-003',
        assignedEmployeeName: 'Ananya Sharma',
        status: 'Locked',
        dueDate: '2026-10-22',
        progress: 0,
      },
      {
        id: 'stg-204',
        projectId: 'prj-002',
        departmentId: 'dept-finance-05',
        departmentName: 'Finance & Payroll Operations',
        departmentColor: '#ec4899',
        sequence: 4,
        assignedEmployeeId: 'emp-006',
        assignedEmployeeName: 'Pooja Iyer',
        status: 'Locked',
        dueDate: '2026-10-30',
        progress: 0,
      },
    ],
    attachments: [],
    comments: [],
    activities: [
      { id: 'pact-201', projectId: 'prj-002', userId: 'user-005', userName: 'Kunal Verma', action: 'Created Project', timestamp: '2026-09-20T10:00:00Z' },
    ],
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
];

export const INITIAL_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'wf-tmpl-01',
    organizationId: 'NP-000001',
    name: 'Standard Client Delivery Pipeline',
    description: 'Sequential 5-stage workflow from Sales contract to IT deployment',
    departmentSequence: [
      { departmentId: 'dept-sales-03', departmentName: 'Sales & Business Growth', color: '#10b981' },
      { departmentId: 'dept-hr-02', departmentName: 'Human Resources & People Ops', color: '#8b5cf6' },
      { departmentId: 'dept-finance-05', departmentName: 'Finance & Payroll Operations', color: '#ec4899' },
      { departmentId: 'dept-ops-06', departmentName: 'Customer Success & Ops', color: '#06b6d4' },
      { departmentId: 'dept-it-04', departmentName: 'IT & Workplace Security', color: '#f59e0b' },
    ],
    isDefault: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'wf-tmpl-02',
    organizationId: 'NP-000001',
    name: 'Internal Audit & Governance Workflow',
    description: 'Sequential compliance check spanning IT, Engineering, HR, and Finance',
    departmentSequence: [
      { departmentId: 'dept-it-04', departmentName: 'IT & Workplace Security', color: '#f59e0b' },
      { departmentId: 'dept-eng-01', departmentName: 'Engineering & Technology', color: '#3b82f6' },
      { departmentId: 'dept-hr-02', departmentName: 'Human Resources & People Ops', color: '#8b5cf6' },
      { departmentId: 'dept-finance-05', departmentName: 'Finance & Payroll Operations', color: '#ec4899' },
    ],
    isDefault: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
];



